name: Deploy to stageing
on:
    push:
        branches:
            - "main"

jobs:
    redploy_everything:
        runs-on: ubuntu-latest
        name: Deploying everything to the staging cluster

        steps: 
            - run: \
                echo ${{ secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key
                ssh -i ~/ssh_key ubuntu@18.181.77.140
                cd ci-monorepo-deployement/ && git pull
                pnpm install
                pnpm run build
                pm2 restart fe-server
                pm2 restart http-server
                pm2 restart ws-server