name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p /home/runner/.ssh

          # Automatically fetch and add the host key
          ssh-keyscan 64.227.147.124 >> /home/runner/.ssh/known_hosts

          chmod 644 /home/runner/.ssh/known_hosts

          ssh -i ~/ssh_key -T ubuntu@64.227.147.124 "
            cd week-25-ci-next-app/ &&
            git pull origin main &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-server &&
            pm2 restart http-server &&
            pm2 restart ws-server
          "
