name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "Checking if SSH key is correct..."
          ls -lah ~/ssh_key
          cat ~/ssh_key | head -n 5  # Print first few lines (DO NOT show full key for security)
          chmod 600 ~/ssh_key
          ssh -v -i ~/ssh_key ubuntu@64.227.147.124 "echo 'SSH connection successful'"

